__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [1]:
a = [[1,2,3], [4,5,6]]
b = [[7,8], [9,10], [11,12]]
c = [[7,8], [9,10], [11,12], [13, 14]]
print(a)
print(b)
print(c)

[[1, 2, 3], [4, 5, 6]]
[[7, 8], [9, 10], [11, 12]]
[[7, 8], [9, 10], [11, 12], [13, 14]]


In [2]:
def matrix_mul(a, b):
    if len(a[0]) != len(b):
        return "Incorrect matrix size for multiplying"
    else:
        c = [[0 for _0 in range(len(b[0]))] for _1 in range(len(a))]
        for ic1 in range(len(c)):
            ib2 = 0
            for i1 in range(len(b[0])):
                counter = 0
                for i2 in range(len(a[0])):
                    counter += a[ic1][i2] * b[i2][ib2]
                c[ic1][i1] = counter
                ib2 += 1
        return c

In [3]:
print(matrix_mul(a, b))

[[58, 64], [139, 154]]


In [4]:
print(matrix_mul(b, a))

[[39, 54, 69], [49, 68, 87], [59, 82, 105]]


In [5]:
print(matrix_mul(c, a))

[[39, 54, 69], [49, 68, 87], [59, 82, 105], [69, 96, 123]]


In [6]:
print(matrix_mul(c, b))

Incorrect matrix size for multiplying


In [7]:
import numpy as np

In [8]:
np.dot(a,b)

array([[ 58,  64],
       [139, 154]])

In [9]:
np.dot(b,a)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]])

In [10]:
np.dot(c,a)

array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105],
       [ 69,  96, 123]])

In [11]:
np.dot(c,b)

ValueError: shapes (4,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)